import turtle
#turtle.penup()
#turtle.begin_fill()
#turtle.goto(100,100)
#turtle.pendown()
#turtle.goto(100,0)
#turtle.goto(0,0)
#turtle.goto(0,100)
#turtle.goto(100,100)
#turtle.end_fill()
#turtle.penup()
#turtle.goto(50,-50)
#turtle.pendown()
#turtle.circle(100)
#turtle.hideturtle()

turtle.pensize(10)
turtle.penup()
turtle.color('blue')
turtle.goto(0,0)
turtle.color('black')
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.goto(100,0)
turtle.color('red')
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.color('yellow')
turtle.goto(200,0)
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.color('green')
turtle.goto(50,-50)
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.goto(150,-50)
turtle.pendown()
turtle.circle(45)




turtle.mainloop()